services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123

  backend:
    build: ./backend
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  redis-data:
